apiVersion: v1
kind: Service
metadata:
  name: app-svc  # The name of the Service; must be unique within the namespace.
  namespace: app        # Specifies the namespace for this Deployment.
  labels:
    app: app      # Labels to categorize or identify the Service, used for grouping.
spec:
  type: NodePort         # Service type; ClusterIP exposes the service only within the cluster.
  selector:              # Specifies which Pods this Service targets based on matching labels.
    app: app      # Targets Pods with the label "app: secure-app".
  ports:                 # Configuration of ports the Service exposes.
    - protocol: TCP      # The protocol used for the Service (TCP is the default).
      port: 80           # The port the Service listens on internally.
      targetPort: 80     # The port on the targeted Pods to which traffic is directed.
