apiVersion: cert-manager.io/v1
kind: ClusterIssuer  # Defines a cluster-wide resource for issuing certificates.
metadata:
  name: letsencrypt-nginx-cert  # Name of the ClusterIssuer for reference in Ingress resources.
spec:
  acme:  # Configuration for Let's Encrypt ACME protocol.
    email: franco.navarro@orion.global  # Email address for Let's Encrypt account creation (required).
    server: https://acme-v02.api.letsencrypt.org/directory  # Production endpoint for Let's Encrypt.
    privateKeySecretRef:
      name: letsencrypt  # Kubernetes Secret to store the private key for the ACME account.
    solvers:  # Define how Let's Encrypt challenges will be solved.
    - http01:  # Uses HTTP01 challenge to verify domain ownership.
        ingress:
          class: nginx  # Specifies the Ingress class to route the challenge request.