apiVersion: networking.k8s.io/v1  # API version for defining an Ingress in Kubernetes.
kind: Ingress                     # Resource type: Ingress to manage external HTTP/S access to services.
metadata:
  name: secure-app-ingress        # Name of the Ingress resource.
  namespace: app           # Namespace where this Ingress resource is created.
  annotations:                    # Annotations provide additional configurations for the Ingress.
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    cert-manager.io/issuer: "selfsigned"
spec:
  ingressClassName: nginx         # Specifies the Ingress controller to be used (e.g., nginx).
  tls:                            # TLS configuration for HTTPS.
  - hosts: 
    - "francotel.com"             # Domain name for the app (replace with your domain).
    secretName: tls-secret        # Secret storing the TLS certificate and key.
  rules:                          # Define routing rules for the Ingress.
  - host: "francotel.com"         # Hostname for routing traffic to this app.
    http:                         # HTTP rules for the host.
      paths:                      # Define the URL paths to route traffic.
      - path: /                   # Root path to match ("/" matches all requests).
        pathType: Prefix          # Matches paths that start with the defined prefix.
        backend:                  # Backend service details.
          service:                # Specifies the service to route traffic to.
            name: app-svc         # Name of the service receiving the traffic.
            port:                 # Port on the service to route traffic to.
              number: 80          # Port number exposed by the service.
